### ISSUE TITLE
Getting Started not working on OSX

### ISSUE THREAD

**Issue by shaban** [matthewmueller/joy#65] opened 2017-12-13 18:04 UTC
Hello, i was quite curious to see joy in action so i tried the getting started Tutorial to get an idea of how joy works. I ran into problems though. I use normal OSX shell no brew or anything .
What happened was this.

Command:
`curl -sfL https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh | sh`

Result:
`matthewmueller/joy: checking GitHub for latest version
matthewmueller/joy: found version 0.1.2 for darwin/amd64
matthewmueller/joy: downloading https://github.com/matthewmueller/joy/releases/download/v0.1.2/joy_0.1.2_darwin_amd64.tar.gz
curl --fail -sSL -o /var/folders/7k/7fcv6h1j4g92mh2ztmcpts6r0000gp/T//joy_0.1.2_darwin_amd64.tar.gz https://github.com/matthewmueller/joy/releases/download/v0.1.2/joy_0.1.2_darwin_amd64.tar.gz
matthewmueller/joy: verifying checksums
curl --fail -sSL -o /var/folders/7k/7fcv6h1j4g92mh2ztmcpts6r0000gp/T//joy_0.1.2_checksums.txt https://github.com/matthewmueller/joy/releases/download/v0.1.2/joy_0.1.2_checksums.txt
install: chmod 755 /usr/local/bin: Operation not permitted
install: /usr/local/bin//joy: Permission denied`

This time as super user (which doesn't do a lot since i should sudo the resulting install.sh i guess):
`sudo curl -sfL https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh | sh`

Result:
`matthewmueller/joy: checking GitHub for latest version
matthewmueller/joy: found version 0.1.2 for darwin/amd64
matthewmueller/joy: downloading https://github.com/matthewmueller/joy/releases/download/v0.1.2/joy_0.1.2_darwin_amd64.tar.gz
curl --fail -sSL -o /var/folders/7k/7fcv6h1j4g92mh2ztmcpts6r0000gp/T//joy_0.1.2_darwin_amd64.tar.gz https://github.com/matthewmueller/joy/releases/download/v0.1.2/joy_0.1.2_darwin_amd64.tar.gz
matthewmueller/joy: verifying checksums
curl --fail -sSL -o /var/folders/7k/7fcv6h1j4g92mh2ztmcpts6r0000gp/T//joy_0.1.2_checksums.txt https://github.com/matthewmueller/joy/releases/download/v0.1.2/joy_0.1.2_checksums.txt
install: chmod 755 /usr/local/bin: Operation not permitted
install: /usr/local/bin//joy: Permission denied`

Now by downloading from releases putting joy executable into GOPATH/bin it seems to work though there is still some rough edges:
`joy run main.go`
Result:
`downloading headless chrome (this only needs to be done once)
/Users/shaban/Library/Preferences/joy/internal/runtime/runtime.go:3:8: could not import github.com/matthewmueller/joy/macro (cannot find package "github.com/matthewmueller/joy/macro" in any of:
	/usr/local/go/src/github.com/matthewmueller/joy/macro (from $GOROOT)
	/Users/shaban/go/src/github.com/matthewmueller/joy/macro (from $GOPATH))
   ⨯ parse error: load error: unable to load the go package: couldn't load packages due to errors: runtime`

Now remedying the situation by manually go getting:
`go get github.com/matthewmueller/joy/macro`

Another Try:
`joy run main.go`
Result working as expected:
`github.com/matthewmueller/joy/macro
hi world!`

Now let's try the serve Command:
`joy serve main.go`
Result:
`cannot find package "../../Downloads" in:
	/Users/Downloads
 FATAL[0000] error serving: load error: unable to load the go package: couldn't load packages due to errors: ../../Downloads`
Downloads just happens to be the directory i put my main.go in.

So either serve command only works with an installable package in GOPATH or am i missing something?

**Comment by matthewmueller** [comment] 2017-12-13 18:42
@shaban thanks for compiling this! This is a good list to make sure I handle all the cases.

I made some assumptions about GOPATH that didn't hold up once you're shipping I binary

I have a fix ready that I just need to cleanup. Should be a much better experience tomorrow :-)

**Comment by shaban** [comment] 2017-12-13 19:12
Thanks for the speedy response.
Looking forward to trying it out.

**Comment by matthewmueller** [comment] 2017-12-14 09:00
Alrighty, could you please try running that command again and let me know if it works?

```
curl -sfL https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh | sh
```

**Comment by Loilo** [comment] 2017-12-14 09:14
I had the same problem, for me it works now. 🎉 
Would be nice to be confirmed by someone else though.

**Comment by matthewmueller** [comment] 2017-12-14 10:37
Woops, still need to fix up this case: 

```
Now let's try the serve Command:
joy serve main.go
Result:
cannot find package "../../Downloads" in: /Users/Downloads FATAL[0000] error serving: load error: unable to load the go package: couldn't load packages due to errors: ../../Downloads
Downloads just happens to be the directory i put my main.go in.
```

**Comment by shaban** [comment] 2017-12-14 13:17
`matthewmueller/joy: checking GitHub for latest version
matthewmueller/joy: found version 0.1.4 for darwin/amd64
matthewmueller/joy: downloading https://github.com/matthewmueller/joy/releases/download/v0.1.4/joy_0.1.4_darwin_amd64.tar.gz
curl --fail -sSL -o /var/folders/7k/7fcv6h1j4g92mh2ztmcpts6r0000gp/T//joy_0.1.4_darwin_amd64.tar.gz https://github.com/matthewmueller/joy/releases/download/v0.1.4/joy_0.1.4_darwin_amd64.tar.gz
matthewmueller/joy: verifying checksums
curl --fail -sSL -o /var/folders/7k/7fcv6h1j4g92mh2ztmcpts6r0000gp/T//joy_0.1.4_checksums.txt https://github.com/matthewmueller/joy/releases/download/v0.1.4/joy_0.1.4_checksums.txt
install: chmod 755 /usr/local/bin: Operation not permitted
install: /usr/local/bin//joy: Permission denied`

Breaking down the steps:
`curl https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh > install.sh`
`sudo sh install.sh`

Result:
`matthewmueller/joy: checking GitHub for latest version
matthewmueller/joy: found version 0.1.4 for darwin/amd64
matthewmueller/joy: downloading https://github.com/matthewmueller/joy/releases/download/v0.1.4/joy_0.1.4_darwin_amd64.tar.gz
curl --fail -sSL -o /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.KZTBXNOF/joy_0.1.4_darwin_amd64.tar.gz https://github.com/matthewmueller/joy/releases/download/v0.1.4/joy_0.1.4_darwin_amd64.tar.gz
matthewmueller/joy: verifying checksums
curl --fail -sSL -o /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.KZTBXNOF/joy_0.1.4_checksums.txt https://github.com/matthewmueller/joy/releases/download/v0.1.4/joy_0.1.4_checksums.txt
matthewmueller/joy: installed as /usr/local/bin/joy`

Trying out if it worked:
`joy run main.go`
Result OK:
`hi world!`

So in a nutshell i think GOPATH problems are fixed now it's just a plain access privilege problem.

Just out of curiosity.

If making your project go-gettable was an option for you, you would probably avoid a lot of minefields since go users are already equipped with a GOPATH and if there is none i think newest go-version comes with a default GOPATH.

And then in most cases GOPATH/bin is inside PATH which means you can ab/use it for all kinds of executables needed like the headless chrome and whatnot. On top you'd benefit from all the abstractions go's build system offers you. On a sidenote what i really love about go is that i know where the files land and how to get rid of them. This makes go users less reluctant to try out some package because they know:

- it installs easily
- they can get rid of it easily
- and their beloved computer doesn't look like node_modules/zillions/of/files ;)

**Comment by matthewmueller** [comment] 2017-12-14 14:52
@shaban I think you're right about this and I am overcomplicating it. 

For some reason, when I first read 1.8 I thought it was coming out, not already out 😅. Then I realized I'm already on 1.9.2! I think relying on 1.8+ is okay, since this is a new project.

The state I need on the client's machine is:

1. Some uncompiled Go source files (stdlib + runtime), so they can be compiled with the rest of the client's program. I may be able to ship `.a` files here too, but I haven't looked into that

For this one, maybe I can just put them where they'd normally be? 

- [ ] Check what happens if you `go get` on top of that sparse directory?
- [ ] Does it still work with forks?

2. I need a version of headless chrome that we control so we can make sure it's consistent.

I think you're right that I can stick this in `$GOPATH/bin`, creating that directory if it doesn't already exist. Since we know where it is, it doesn't need to be in the user's `$PATH`.

- [ ] Move headless chrome into `$GOPATH/bin`

Does that make sense?

**Comment by shaban** [comment] 2017-12-14 17:15
ok trying to understand a bit what's going on.

for understanding what is happening i simply deleted all your packages in pkg and did a
`go get -u github.com/matthewmueller/joy`

Result:
a "joy.a" file in GOPATH/pkg/matthewmueller of 450 bytes length so doesn't sound like the real deal.

Next i tried to get the sub packages and all looks neat. They appear as go archives like you said.
So basically a joy cmd executable package that has all the core packages as local non relative imports should do the job.

On headless chrome:
Basically you download a snapshot of chromium that is new enough to support the headless flag.
from what i understand this is a standalone zip package you can put wherever you want, as long as you can run it from that place. So best would be GOPATH/bin or whatever other directory you don't need extra privileges for execution that lies within a reasonable scope (not cluttering users system).

While looking at your code that downloads chromium i think thats in general a good approach.
You don't have to rely on the posix shell tools since they won't do anything for you that net/http +os + runtime can't do for you either.

So to recapitulate:
- use a **non system** preferably GOPATH specific path to install external executables.
- use the standard way to go get joy into -> GOPATH/bin/joy.
- have the core libraries  as non relative local imports so they get pulled in by installing joy.
- use go to bootstrap your non go specific external dependencies like you did for downloading chromium.

am i missing something?

**Comment by matthewmueller** [comment] 2017-12-16 18:03
ahh yep, that's fixed in master i think. I've been adding a bunch of tests to this pipeline as well as simplifying things, so I think the next release will be pretty solid

**Comment by matthewmueller** [comment] 2017-12-17 09:34
Okay, I think I've squashed the major issues in the latest release 0.1.6. 

- install the master development version with: `go get -u -v github.com/matthewmueller/joy...`

- or upgrade to the latest production release: `joy upgrade` or `curl -sfL https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh | sh`

**Comment by shaban** [comment] 2017-12-18 19:31
Well i go the `go get` way, so that it lands where i expect it.
And that works really nicely.
The usr/local problem doesn't happen at all to me now.

IMHO in modern unix `/usr/...` should be used by package manager(s)/OS and thats it.

**Comment by matthewmueller** [comment] 2017-12-19 04:45
/cc @caarlos0

Any recommendations on this? I'm using godownloader which installs to `/usr/local/bin`. Should this be changed? I'm not sure where else it'd be placed though.

**Comment by shaban** [comment] 2017-12-19 07:15
Just a question, since i assume you want to have a prospering ecosystem of reusable code / components etc. at some point.

Why not use $HOME/joy on linux and userprofile/joy on windows.
This place could be a stub for some sort of package system later on.

**Comment by matthewmueller** [comment] 2017-12-19 07:29
Most of the shared components and things will be in `$GOPATH`, we just have a few things like the runtime which need to be compiled alongside the source. I'm definitely open to changing this, in fact we could stick them in $GOPATH too, but they just can't be in the exact same place as they'd break `go get`, so maybe under `.joy` instead. 

Not a huge fan of `$HOME/...` clutter but I could be convinced if others prefer that. Right now, I'm using these settings: https://github.com/sindresorhus/env-paths to choose the config path.

**Comment by caarlos0** [comment] 2017-12-19 11:09
> Any thoughts on this? I'm using godownloader which installs to /usr/local/bin. Should this be changed? I'm not sure where else it'd be placed though.

it should be ok to install to /usr/local/bin, either way, it can be overwritten with the `-b` flag:

```sh
curl -sfL https://raw.githubusercontent.com/matthewmueller/joy/master/install.sh | sh -s -- -b /tmp
```

**Comment by matthewmueller** [comment] 2017-12-19 14:05
@caarlos0 ahh okay awesome, thanks for chiming in!

Going to close this since I think this issue should be solved. Will add a note in the readme if anyone else runs into this.

**Closed** 2017-12-19 14:05 UTC
Labels: bug, needs info
